algo=input('\nDigite algo: ')
print('-' *50)

print(f'O tipo primitivo desse valor é {type(algo)}')
print(f'Só tem espaços? ------ {algo.isspace()}')
print(f'É um número? --------- {algo.isnumeric()}')
print(f'É alfabético? -------- {algo.isalpha()}')
print(f'É alfanumérico? ------ {algo.isalnum()}')
print(f'Está em maiúsculas? -- {algo.isupper()}')
print(f'Está em minúsculas? -- {algo.islower()}')
print(f'Está capitalizada? --- {algo.istitle()}')
print(f'É imprimivel --------- {algo.isprintable()}')
print(f'É um decimal --------- {algo.isdecimal()}')
print(f'É um digito ---------- {algo.isdigit()}')

print('-' *50)