// Essa que é a estrutura básica do
// programa é que tem a palavra algoritmo.
// Vai ter início e fim.


Algoritmo "Olá Mundo"

Var


Inicio

      escreval("Bom dia!") // "l" Vai escrever quebrando a linha
      escreva("Boa noite!") //Vai escrever na tela sem quebra de linha.

Fimalgoritmo


//	Lembrando que você tem que respeitar
//	a sintaxe da linguagem,
//	que é abrir e fechar parênteses.

